version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: artisanalbaguette
      MONGO_INITDB_ROOT_PASSWORD: 6ShwDWr64l8E0l5v
    command: ["mongod", "--auth", "--bind_ip_all"]

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://chatappuser:chatappuserpass@mongo:27017/chatApp
      - NODE_ENV=development
    depends_on:
      - mongo
